### ISSUE TITLE
Nucleator (sometimes) gains twice as many stacks when picking up an item

### ISSUE THREAD

**Issue by aka-Syntax** [Moffein/Starstorm2Unofficial#11]
![image](https://github.com/Moffein/Starstorm2Unofficial/assets/122943451/e13ab2b3-c13e-4bef-9475-8dafa765d3c5)
no clue what is happening here. i'll boot up a run and then at some point he will just start picking up multiple stacks of items for no reason. 

log in case it helps, probably
[message.txt](https://github.com/Moffein/Starstorm2Unofficial/files/14591148/message.txt)

lmk if you need anything else

**Comment by Moffein** [comment]
Could you export your mod profile as a file and upload it here so I can take a look at it?

**Comment by aka-Syntax** [comment]
it says github doesn't support .r2z files so is a code ok
018e3934-c0c0-9ddb-61db-1b282e970da5

**Comment by aka-Syntax** [comment]
i heart nucleator
