### ISSUE TITLE
Enabling the void field changes can cause 2 nemesis spawn

### ISSUE THREAD

**Issue by DarSitam** [Moffein/Starstorm2Unofficial#13]
Picking up the cuffs, and leaving the void fields will spawn 2 nemesis

2 examples below :

nemmando from SS2U and nemforcer from SS2
![20240323235754_1](https://github.com/Moffein/Starstorm2Unofficial/assets/106157297/23c86905-413d-4427-a707-e53e45411294)

nemforcer from SS2U and nemmando from SS2 (SS2U nemmando was disabled)
![20240324000249_1](https://github.com/Moffein/Starstorm2Unofficial/assets/106157297/6c933892-0d00-48e2-87a5-b1010acfe5f8)

Probably not a bug since it's technically 2 different events, but i think a check should be added since there's a compatibility for SS2 nemesises

**Comment by Moffein** [comment]
There's an option in the config to disable the mod's Nemesis Invasion Event so that it doesn't overlap with SS2 Official's. Official also has a config to disable its event if you want to use SS2U's nemesis event instead, though I don't think SS2U's nemesis event triggers unlocks for SS2O.
