### ISSUE TITLE
Sound of Nucleator's Fission Impulse Attack is too loud

### ISSUE THREAD

**Issue by PlanteTropGrasse** [Moffein/Starstorm2Unofficial#14]
I just tested the character Nucleator  and noticed that the sound level of the ability  "Fission Impulse" is clearly too high compared to everything else in the game. I'm using your mod without any other one.

Thank you very much for your mod, I absolutely love it.

**Comment by Moffein** [comment]
Thanks for reporting this!
The skill uses Loader's alt special SFX, which got broken in the Devotion update to be super loud and mapwide.

You can use this mod to fix it:
https://thunderstore.io/package/Prototype/Underslam/

**Comment by Moffein** [comment]
Reopening this for visibility until the bug is fixed in Vanilla.
