### ISSUE TITLE
[Minor Issues] Nemesis Commando's sword texture and Executioner skills

### ISSUE THREAD

**Issue by Thorebourne** [Moffein/Starstorm2Unofficial#16]
the texture for Nemesis Commando's sword in the lobby seems to change if you quit the game while using an ability that changes it, like Distant Gash. the sword remains like that on specific skin even if you use a different one, but it seems to correct itself once you attack with the sword in game or do a full restart. it also seems like his "Classic" skin starts like this, and after returning to the lobby it also corrects itself. additionally, whenever i select Executioners "Standard-Issue Pistol" skill, it resets to the default after restarting the game.

**Comment by Moffein** [comment]
Thanks for reporting this, I'll be working on a fix.

**Comment by Moffein** [comment]
Executioner's skill stuff will be fixed in the next update.
I took a look at the Nemmando issue, but unfortunately I won't be able to fix it, as it is a complex issue involving a lot of deeply-seated code that I wasn't originally around for when it was written.
