### ISSUE TITLE
[Minor Issue] Classic Commando skin and Executioner don't go transparent when looking up

### ISSUE THREAD

**Issue by Thorebourne** [Moffein/Starstorm2Unofficial#17]
i notice that whenever i was using the Classic skin for Commando, and whenever i was playing Executioner, they don't go transparent/dithered when looking up like other characters do. it happens with all of Executioner's skins too.
![20240819121238_1](https://github.com/user-attachments/assets/b948624b-9bd7-4caa-9995-47b17c5a92bb)
![20240819121310_1](https://github.com/user-attachments/assets/36dbf827-547f-4bed-b606-a48edaefca48)
![20240819121321_1](https://github.com/user-attachments/assets/73bdb051-a3c5-4171-9b42-221a4e847a9b)
the first screenshot shows what should happening, and the last two show what it looks like in game

**Comment by Thorebourne** [comment]
i just tested it, it also seems to happen to Cyborg, Chirr, Nucleator, and Pyro, but _not_ Nemmando

**Comment by Moffein** [comment]
Thanks for reporting this, let me know if the latest update fixed it.

**Comment by Thorebourne** [comment]
it seemed to fix everything except Commando's skin

**Comment by Moffein** [comment]
Seems like I forgot to fix that one as well, uploaded another fix for it.
