### ISSUE TITLE
All mod-added items are disabled

### ISSUE THREAD

**Issue by Zenithtech35** [Moffein/Starstorm2Unofficial#23]
No matter whether I'm playing all vanilla with only the current version of the mod and it's prerequisites, or a heavily modded game, all of the items added by the mod do not appear at all. Neither in game nor in the logbook; while the characters, Typhoon difficulty and storms appear and work properly. This does not change if I set the "SS2 Official - Autoconfig" setting to false, and I do not have Starstorm 2 Official installed. After reverting to the previous version all items return to normal.

**Comment by Moffein** [comment]
Post your log and I'll take a look.
You can find it by going to Settings -> Locations -> Browse Profile Folder -> BepInEx/LogOutput.log

**Comment by Moffein** [comment]
I've identified the issue and uploaded a fix.

**Comment by Zenithtech35** [comment]
> I've identified the issue and uploaded a fix.

Wow! Very fast! Thanks a lot for your hard work! Sorry I didn't see your first reply
