### ISSUE TITLE
Common item tier not working

### ISSUE THREAD

**Issue by EfJun1** [Moffein/Starstorm2Unofficial#24]
Common item tier not working, doesn't show up on logbook nor in game. I tested with my profile and green tier & red tier items overwrite starstormofficial items. Unsure what is the issue.

This is my profile : 019252be-2d27-8283-ed18-2cb81a07da4d
![Risk_of_Rain_2_bc2jKTEirA](https://github.com/user-attachments/assets/39bfdc12-680b-4a62-87ff-146f8b892b55)

**Comment by Moffein** [comment]
SS2 Unofficial disables items duplicated in SS2 Official by default. If you would like all of SS2 Unofficial's items, you will need to go to your config and disable the Autoconfig setting, and manually disable conflicting features such as Storms and Void instead.

**Comment by EfJun1** [comment]
> SS2 Unofficial disables items duplicated in SS2 Official by default. If you would like all of SS2 Unofficial's items, you will need to go to your config and disable the Autoconfig setting, and manually disable conflicting features such as Storms and Void instead.

Alright, thank you very much for the answer.
