### ISSUE TITLE
Feature Request: Missing Sound Effects

### ISSUE THREAD

**Issue by Kuusotare** [Moffein/Starstorm2Unofficial#3]
Absolutely amazing to be able to play with Chirr again, as well as experimenting with the other features alongside SS2 official. One QoL feature that'd be amazing is some sound effects for Chirr and Cyborg on skill use, even recycled sounds for some auditory feedback to make them feel a little more lively would be amazing.

Again, thanks so much.

**Comment by Moffein** [comment]
Tested a fresh install, and Chirr/Cyborg SFX seem to be working on my end. Try reinstalling and let me know if the issue persists.

**Comment by dsput** [comment]
I am also having this issue, despite doing a fresh reinstall - as well as testing with an older version of SS2U. Issue persists. Video attached. Also occurs with M1 and abilities on Cyborg. Strangely enough, Pyro seemingly has all sound effects intact.

https://user-images.githubusercontent.com/124550501/220803715-8c209315-c060-4e84-96ce-b1ff5af92917.mp4

**Comment by Kuusotare** [comment]
Unfortunately a fresh install yields the same results as the video above, no SFX on Chirr and Cyborg. Pyro does have sound effects, as reported.

**Comment by dsput** [comment]
Update: Downgraded to 0.9.3 - Chirr's "Take Flight" sound effect while floating plays, but no other sounds have come back/begun working again.
Upgrading to latest releases causes sound to break again.

**Comment by Moffein** [comment]
Looked into it, and it seems like there were some remaining conflicts with official SS2. Latest update should fix this, lemme know if it works.

**Comment by dsput** [comment]
That fixed it, thank you!

**Comment by Kuusotare** [comment]
Did the trick. Perfect.
