### ISSUE TITLE
Suggestion for Better Command Artifact (but it doesn't have an issues page. so I came here)

### ISSUE THREAD

**Issue by Darkmega18** [Moffein/Starstorm2Unofficial#4]
G'day. Sorry in advance, but I wanted to post this to the better command artifact fork repository but it didn't have an issues tab. So since this was your pinned repository and you'd recently posted to another issue here, I figured I'd just place it here to make the problem known for next time.

_Anyways:_

I saw that your version of better command artifact claims to not have issues with some special items like the relic of energy from forgotten relics among other things over better command essence and boops original mod. So I made a switch over to it. But I'm finding that now there are just some things missing now. :<

I'd like to ask if you'd be able to add some features to it similar to better command essence so that this can be the best of the command artifact rebalance mods (with the least amount of issues possibly):

- Such as having per tier selection numbers (white, green, red, void tiers, void potentials/void key potentials, lunar, equipment, lunar equipment, boss.)
- allowing printers and scrappers etc to continue spawning
- Ability to not modify the drops from printers, multi-shops/shipping/adaptive chests
- items dropped when inside the bazaar/lunar store etc aren't commanded.
- Possibly even being able to use recycler equipment on an item re-rolls the selections from the command item in question/converts it into a command essence to be rechosen if it's already become an item?

Possibly even adding risk of options support with a global switch that can turn on and off the mechanic changes so that both can be enjoyed (a more balanced command, and a fully unhinged command) at the flick of the switch.

**Comment by Moffein** [comment]
Unfortunately, I'm currently not working on developing additional functionality for any of my mods.

**Comment by Darkmega18** [comment]
aww... feature freeze time?

**Comment by Darkmega18** [comment]
aw... :< well, alrighty then.
