### ISSUE TITLE
[BUG-literally] Chirr's Hp freaking out on client

### ISSUE THREAD

**Issue by Thresh90** [Moffein/Starstorm2Unofficial#6]
Essentially, whenever a client is playing Chirr and they befriend an enemy, the hp bar on their side visually shoots up to an irregular amount of hp.

It might have something to do with the buff recieved when befriending an enemy

**Comment by Moffein** [comment]
Send a console log next time it happens, and I'll take a look.

**Comment by Thresh90** [comment]
turns out it was holy dll causing issue, false alarm !
